version: "3.3"

services:
  geoip-php:
    image: geoip:$GEOIP_APP_V
    build: .
    volumes:
      - ./webpage/:/var/www/html
    environment:
      USER: root
      PASSWORD: $DB_PASSWORD
      DBNAME: ip_query
      HOSTNAME: mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoip-php.rule=Host(`geoip-php.localtest.me`)"
      - "traefik.http.services.geoip-php.loadbalancer.server.port=80"
      - "traefik.http.routers.geoip-php.entrypoints=websecure"
      - "traefik.http.routers.geoip-php.tls=true"
    networks:
      - traefik-public
      - backend

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - /var/lib/mysql
      - ./dbinit/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
    networks:
     - backend

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localtest.me`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
    networks:
      - traefik-public
      - backend
networks:
  traefik-public:
    external: true
  backend: