version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: haslo
    networks:
     - backend
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localtest.me`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
    networks:
      - traefik-public
      - backend

networks:
  traefik-public:
    external: true
  backend:
